apiVersion: servicecatalog.k8s.io/v1beta1
kind: ClusterServiceBroker
metadata:
  name: vault-broker
spec:
  url: http://vault-broker.vault-broker.svc.cluster.local:8080
  authInfo:
    basic:
      secretRef:
        name: vault-broker
        namespace: vault-broker