kind: Service
apiVersion: v1
metadata:
  name: vault-broker
  namespace: vault-broker
  labels:
    app: vault-broker
  annotations:
    spring.cloud.gateway/routes: |
      predicates:
      - Host=vault-broker.k8s.bosh.tokyo
      filters:
      - RequestLogging=
      - PreserveHostHeader=
spec:
  selector:
    app: vault-broker
  ports:
  - protocol: TCP
    port: 8080
    name: http