kind: Service
apiVersion: v1
metadata:
  name: vault-broker
  namespace: vault-broker
  labels:
    app: vault-broker
spec:
  selector:
    app: vault-broker
  ports:
  - protocol: TCP
    port: 8080
    name: http